services:
  postgres:
    image: postgres:15
    container_name: axum_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - ./db-seed:/docker-entrypoint-initdb.d

  jaeger:
    image: jaegertracing/jaeger:2.6.0
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"  # Jaeger UI
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP
      - "5778:5778"    # Agent configs
      - "9411:9411"    # Zipkin

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clean_axum_app
    depends_on:
      - postgres
      - jaeger
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://testuser:pass@axum_postgres:5432/testdb
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318/v1/traces
